var Config = require("config");
var Good = require("good");
var GoodConsole = require("good-console");

// Good (logging to the console)
exports.good = {

    register: Good,
    options: {
        reporters: [{
            reporter: GoodConsole,
            events: {
                //ops: "*",
                log: "*", // maps to the "log" event 
                response: "*", // maps to either the "response" or "tail" event
                error: "*", // maps to the "request-error" event
                request: "*" // maps to the hapi "request" event (generated by request.log())
            }
        }]
    }

};

