// the NODE_ENV env variables should be defined before the node process is started; 
// if not defined we use the following defaults;
process.env.NODE_ENV = process.env.NODE_ENV || "dev";

console.log("process.env.NODE_ENV: ", process.env.NODE_ENV);

// the above env variables must be defined before the config module is first required
var Path = require("path");
var Config = require("config");
var Hoek = require("hoek");
var Glue = require('glue');
var Utils = require("./common/utils");
var Seneca = require("./common/seneca");

internals = {};

// add custom filters and globals to the nunjucks template engine
//Utils.configureNunjucks();

var manifest = {
    server: JSON.parse(JSON.stringify(Config.get("hapi.server"))),

    connections: [
        {
            host: "localhost",
            port: Config.get("port")
        }
    ],

    plugins: [
        {
            "good": {
                reporters: [{
                    reporter: require("good-console"),
                    events: {
                        //ops: "*",
                        log: "*", // maps to the "log" event 
                        response: "*", // maps to either the "response" or "tail" event
                        error: "*", // maps to the "request-error" event
                        request: "*" // maps to the hapi "request" event (generated by request.log())
                    }
                }]
            }
        },

        // {
        //     "chairo": {
        //         //log: "silent"
        //     }
        // },

        {
            "blipp": {
                showAuth: true
            }
        },

        {
            "inert": {

            }
        },

        {
            "vision": {

            }
        },

        {
            "tv": {
                host: "localhost",
                port: 6002,

            }
        },

        {
            "hapi-auth-cookie": {

            }
        },
        /**/        
        {   
            "./web": {

            }
        },

        {   
            "./api": {
                "abc": 123

            }
        }

    ]
};

// TODO: remove good console if not in production
// TODO: migrato to hapi 9
var options = {
    relativeTo: __dirname,
    prePlugins: function(server, next){
        next();
    }
};

Glue.compose(manifest, options, function (err, server) {

    Hoek.assert(!err, 'Failed registration of one or more plugins: ' + err);

    Utils.configureNunjucks2(server);

    // start the server and finish the initialization process
    server.start(function(err) {

        Hoek.assert(!err, 'Failed start server: ' + err);

        Utils.registerServer(server);

        
        console.log('Server started at: ' + server.info.uri);
        console.log("Hapi version: " + server.version);
    });
});
/*
*/
