#!/bin/bash
wget http://v2.redeconvergir.net/projects/1/jornalTU.pdf
wget http://v2.redeconvergir.net/projects/2/tamera.pdf
wget http://v2.redeconvergir.net/projects/49/InformacaodeFundo.pdf
wget http://v2.redeconvergir.net/projects/54/CINEMAA4PRINT.pdf
wget http://v2.redeconvergir.net/projects/56/Logo8pdf.pdf
wget http://v2.redeconvergir.net/projects/58/CursoPermacultura22deJulho.pdf
wget http://v2.redeconvergir.net/projects/81/Folheto5ELEMENTOS.pdf
wget http://v2.redeconvergir.net/projects/98/ApresentaogeraldoProjetoRios20072012.pdf
wget http://v2.redeconvergir.net/projects/99/ApresentaogeraldoProjetoRios20072012.pdf
wget http://v2.redeconvergir.net/projects/100/ApresentaogeraldoProjetoRios20072012.pdf
wget http://v2.redeconvergir.net/projects/101/ApresentaogeraldoProjetoRios20072012.pdf
wget http://v2.redeconvergir.net/projects/102/panfletoTROKAKI.pdf
wget http://v2.redeconvergir.net/projects/104/Apresentao.pdf
wget http://v2.redeconvergir.net/projects/117/ApresentaodeNutrimeiogenerico.pdf
wget http://v2.redeconvergir.net/projects/183/estatutosCirculos3.pdf
wget http://v2.redeconvergir.net/projects/202/panfleto.pdf
wget http://v2.redeconvergir.net/projects/206/DifusoCoopApresentao.pdf
wget http://v2.redeconvergir.net/projects/239/EstatutosAACRAssociaodeAgroecologiaeCulturaRegenerativa092014.pdf
wget http://v2.redeconvergir.net/projects/250/ApresentaoCIDADEMAIS15.pdf
wget http://v2.redeconvergir.net/projects/254/Projeto.pdf
